import { useEffect, useMemo, useRef, useState, type FormEvent, type ReactNode } from 'react'
import { Link, NavLink, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import { api, ils, send, type Account, type AdminData, type Entry, type MerchantData, type Order, type Product, type Store } from './api'

const exampleStores:Store[] = [
  {id:'preview-phone',slug:'preview-phone',name:'חנות דיגיטל',category:'דיגיטל',description:'מוצרים שימושיים ליום יום.',city:'',logo_url:''},
  {id:'preview-style',slug:'preview-style',name:'חנות אופנה',category:'אופנה',description:'פריטים עם אופי.',city:'',logo_url:''},
]
const exampleProducts:Product[] = [
  {id:'preview-1',store_id:'preview-phone',slug:'tablet',name:'טאבלט 10.9 אינץ׳',category:'דיגיטל',description:'פריט להמחשת תצוגת המוצרים.',price_agorot:199900,image_url:'',stock:4,variants_json:'[]',store_name:'חנות דיגיטל',store_slug:'preview-phone'},
  {id:'preview-2',store_id:'preview-style',slug:'shoes',name:'נעליים אלגנטיות',category:'אופנה',description:'פריט להמחשת תצוגת המוצרים.',price_agorot:27900,image_url:'',stock:8,variants_json:'[]',store_name:'חנות אופנה',store_slug:'preview-style'},
]
const Preview = () => <p className="preview-note" role="status">תצוגה לדוגמה · החנויות והמוצרים יוצגו כאן לאחר חיבור המסד והוספת חנויות.</p>
const Arrow = () => <span aria-hidden="true">←</span>
const Icon = ({name}:{name:'bag'|'search'|'menu'|'close'}) => <span className="icon" aria-hidden="true">{name==='bag'?'♙':name==='search'?'⌕':name==='menu'?'☰':'×'}</span>
const initials = (name:string) => name.trim().slice(0,2)
function Art({product,large=false}:{product?:Product;large?:boolean}) {
  const [broken,setBroken]=useState(false)
  return <div className={`product-art ${large?'large':''} tone-${product?.category.includes('אופנה')?'peach':'sage'}`}>
    {product?.image_url && !broken ? <img src={product.image_url} alt="" loading="lazy" onError={()=>setBroken(true)} /> :
      <div className="abstract-product" aria-hidden="true"><span className="abstract-disc" /><span className="abstract-arch" /></div>}
  </div>
}
function Header({count,user,onCart}:{count:number;user:Account|null;onCart:()=>void}) {
  const [menu,setMenu]=useState(false)
  return <>
    <div className="announcement">מקום אחד. הרבה חנויות מקומיות. <span aria-hidden="true">✦</span> ברוכים הבאים למדרום</div>
    <header className="site-header">
      <div className="header-inner">
        <Link to="/" className="brand" aria-label="מדרום, לדף הבית"><span className="brand-symbol">מ</span><span>מדרום<small>הקניון הדיגיטלי</small></span></Link>
        <nav className={menu?'nav open':'nav'} aria-label="ניווט ראשי" onClick={()=>setMenu(false)}>
          <NavLink to="/" end>בית</NavLink><NavLink to="/stores">חנויות</NavLink><NavLink to="/catalog">כל המוצרים</NavLink>
          <NavLink to="/for-business">לבעלי עסקים</NavLink><NavLink className="mobile-only" to={user ? user.role==='admin'?'/admin':'/merchant':'/login'}>כניסת עסקים</NavLink>
        </nav>
        <div className="header-actions">
          <Link className="quiet-action desktop-only" to={user ? user.role==='admin'?'/admin':'/merchant':'/login'}>{user?'אזור ניהול':'כניסת עסקים'}</Link>
          <button className="icon-button cart-trigger" type="button" aria-label={`פתיחת הסל, ${count} פריטים`} onClick={onCart}><Icon name="bag"/>{count>0&&<span className="cart-count">{count}</span>}</button>
          <button className="icon-button mobile-only" type="button" aria-label={menu?'סגירת תפריט':'פתיחת תפריט'} aria-expanded={menu} onClick={()=>setMenu(!menu)}><Icon name={menu?'close':'menu'}/></button>
        </div>
      </div>
    </header>
  </>
}
function Footer() {return <footer className="site-footer"><div className="wrap footer-grid"><div><Link className="brand" to="/"><span className="brand-symbol">מ</span><span>מדרום<small>הקניון הדיגיטלי</small></span></Link><p>מרחב אחד לחנויות מקומיות.<br/>כל חנות מביאה איתה סיפור משלה.</p></div><div><strong>לגלות</strong><Link to="/catalog">כל המוצרים</Link><Link to="/stores">החנויות</Link></div><div><strong>לעסקים</strong><Link to="/for-business">איך מצטרפים</Link><Link to="/login">כניסה למערכת</Link></div><div><strong>מידע</strong><Link to="/privacy">פרטיות</Link><Link to="/accessibility">נגישות</Link></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} מדרום</span><span>נבנה עבור עסקים מקומיים</span></div></footer>}
function ProductCard({product,add,preview}:{product:Product;add:(product:Product)=>void;preview:boolean}) {
  let hasVariants=false;try{hasVariants=(JSON.parse(product.variants_json||'[]') as unknown[]).length>0}catch{}
  return <article className="product-card"><Link to={`/product/${product.id}`} aria-label={`פרטי ${product.name}`}><Art product={product}/></Link><div className="product-meta"><Link to={`/store/${product.store_slug}`} className="store-label">{product.store_name}</Link><Link className="product-title" to={`/product/${product.id}`}>{product.name}</Link><div className="price-line"><strong>{ils(product.price_agorot)}</strong>{hasVariants?<Link className="round-add" to={`/product/${product.id}`} aria-label={`בחירת אפשרות ל${product.name}`}>←</Link>:<button type="button" className="round-add" disabled={preview||product.stock<1} onClick={()=>add(product)} aria-label={`הוספת ${product.name} לסל`}>+</button>}</div>{product.stock<1&&<small>אזל מהמלאי</small>}</div></article>
}
function Home({stores,products,preview,add}:{stores:Store[];products:Product[];preview:boolean;add:(product:Product)=>void}) {
  return <main>
    <section className="hero"><div className="wrap hero-layout"><div className="hero-content"><span className="eyebrow"><span className="tiny-star">✳</span> קונים מקומי. מוצאים יותר.</span><h1>דברים טובים<br/>קורים <em>קרוב.</em></h1><p>החנויות שאתם אוהבים נפגשות במקום אחד. לגלות, לבחור ולחזור לקנות קרוב לבית.</p><div className="hero-actions"><Link className="button dark" to="/catalog">בואו לגלות <Arrow/></Link><Link className="text-button" to="/stores">החנויות שלנו <Arrow/></Link></div><span className="hero-footnote">כל חנות, הסיפור והמוצרים שלה.</span></div><div className="hero-art" aria-label="תצוגה מעוצבת של מוצרים"><div className="hero-sun"/><div className="hero-illustration hero-main"><div className="mini-art"><span/></div><small>חפצים עם אופי</small><strong>למצוא משהו<br/>בדיוק בשבילכם.</strong></div><div className="hero-illustration hero-small"><small>מדרום מציגים</small><strong>מקום אחד.<br/>הרבה חנויות.</strong><span>↗</span></div><div className="hero-seal">מקומי<br/>זה אישי</div></div></div></section>
    <section className="value-strip"><div className="wrap value-grid"><span>01 <strong>מגלים חנויות</strong></span><span>02 <strong>מוצאים את הפריט</strong></span><span>03 <strong>תומכים בעסק מקומי</strong></span></div></section>
    <section className="section wrap"><div className="section-heading"><div><span className="eyebrow">קצת מעבר לפינה</span><h2>החנויות במדרום<span className="dot">.</span></h2></div><Link className="text-button" to="/stores">לכל החנויות <Arrow/></Link></div>{preview&&<Preview/>}<div className="store-grid">{stores.map((s,i)=><Link to={`/store/${s.slug}`} className={`store-tile store-tone-${i%3}`} key={s.id}><span className="store-monogram">{initials(s.name)}</span><span className="store-tile-copy"><small>{s.category}</small><strong>{s.name}</strong><span>{s.city||'מדרום'}</span></span><Arrow/></Link>)}</div></section>
    <section className="section products-section"><div className="wrap"><div className="section-heading"><div><span className="eyebrow">נבחר בשבילכם</span><h2>מה חדש בחנויות<span className="dot">.</span></h2></div><Link className="text-button" to="/catalog">לכל המוצרים <Arrow/></Link></div><div className="product-grid">{products.slice(0,4).map(p=><ProductCard key={p.id} product={p} preview={preview} add={add}/>)}</div></div></section>
    <section className="business-banner wrap"><div><span className="eyebrow">יש לכם חנות?</span><h2>הסיפור שלכם<br/>ממשיך גם בדיגיטל.</h2><p>מקום לחנות שלכם, למוצרים שלכם ולדרך שבה אתם מנהלים את העסק.</p><Link to="/for-business" className="button light">גלו איך מצטרפים <Arrow/></Link></div><span className="banner-mark" aria-hidden="true">מ</span></section>
  </main>
}
function Catalog({products,preview,add}:{products:Product[];preview:boolean;add:(p:Product)=>void}) {
  const [search,setSearch]=useState(''),[category,setCategory]=useState('הכול'),[sort,setSort]=useState('new')
  const categories=['הכול',...new Set(products.map(p=>p.category).filter(Boolean))]
  const filtered=useMemo(()=>products.filter(p=>(category==='הכול'||p.category===category)&&(`${p.name} ${p.store_name} ${p.description}`).toLocaleLowerCase('he').includes(search.toLocaleLowerCase('he'))).sort((a,b)=>sort==='low'?a.price_agorot-b.price_agorot:sort==='high'?b.price_agorot-a.price_agorot:0),[products,search,category,sort])
  return <main className="wrap inner-page"><div className="page-intro"><span className="eyebrow">מקום לגלות</span><h1>כל המוצרים<span className="dot">.</span></h1><p>דפדפו, סננו ומצאו את הדבר הבא שלכם.</p></div>{preview&&<Preview/>}<div className="catalog-tools"><label className="search-field"><span className="sr-only">חיפוש מוצרים וחנויות</span><Icon name="search"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="מה מחפשים היום?"/></label><label className="sort-field">מיון <select value={sort} onChange={e=>setSort(e.target.value)}><option value="new">הכי חדשים</option><option value="low">מחיר מהנמוך</option><option value="high">מחיר מהגבוה</option></select></label></div><div className="chips" aria-label="סינון לפי קטגוריה">{categories.map(c=><button type="button" key={c} aria-pressed={category===c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><p className="result-count" role="status">{filtered.length} מוצרים</p>{filtered.length?<div className="product-grid">{filtered.map(p=><ProductCard key={p.id} product={p} preview={preview} add={add}/>)}</div>:<Empty text="לא נמצאו מוצרים. אפשר לנסות חיפוש אחר."/>}</main>
}
function Stores({stores,preview}:{stores:Store[];preview:boolean}) {return <main className="wrap inner-page"><div className="page-intro"><span className="eyebrow">האנשים שמאחורי המוצרים</span><h1>החנויות שלנו<span className="dot">.</span></h1><p>כל עסק מביא את הסיפור שלו. כאן אפשר להכיר אותם.</p></div>{preview&&<Preview/>}<div className="store-grid">{stores.map((s,i)=><Link to={`/store/${s.slug}`} className={`store-tile store-tone-${i%3}`} key={s.id}><span className="store-monogram">{initials(s.name)}</span><span className="store-tile-copy"><small>{s.category}</small><strong>{s.name}</strong><span>{s.city||'מדרום'}</span></span><Arrow/></Link>)}</div>{!stores.length&&<Empty text="החנויות הראשונות יופיעו כאן בקרוב."/>}</main>}
function StorePage({stores,products,preview,add}:{stores:Store[];products:Product[];preview:boolean;add:(p:Product)=>void}) {const {slug}=useParams(),store=stores.find(s=>s.slug===slug);if(!store)return <Missing/>;const items=products.filter(p=>p.store_id===store.id);return <main><section className="store-hero"><div className="wrap"><Link to="/stores" className="back-link">לכל החנויות <Arrow/></Link><div className="store-title"><span className="store-monogram">{initials(store.name)}</span><div><span className="eyebrow">{store.category} · {store.city||'מדרום'}</span><h1>{store.name}</h1><p>{store.description}</p></div></div></div></section><div className="wrap section"><h2>המוצרים בחנות<span className="dot">.</span></h2>{preview&&<Preview/>}<div className="product-grid">{items.map(p=><ProductCard key={p.id} product={p} preview={preview} add={add}/>)}</div>{!items.length&&<Empty text="עדיין אין מוצרים בחנות הזו."/>}</div></main>}
function ProductPage({products,preview,add}:{products:Product[];preview:boolean;add:(p:Product)=>void}) {const {id}=useParams(),[choice,setChoice]=useState(''),product=products.find(p=>p.id===id);if(!product)return <Missing/>;let variants:Array<{name:string,stock:number}>=[];try {variants=JSON.parse(product.variants_json||'[]')}catch{}return <main className="wrap inner-page"><Link className="back-link" to="/catalog">בחזרה למוצרים <Arrow/></Link><div className="detail-grid"><Art product={product} large/><div className="detail-copy"><Link to={`/store/${product.store_slug}`} className="eyebrow">{product.store_name}</Link><h1>{product.name}</h1><strong className="detail-price">{ils(product.price_agorot)}</strong><p>{product.description||'פרטים נוספים על המוצר יתווספו בקרוב.'}</p>{variants.length>0&&<label className="field">בחירת אפשרות<select value={choice} onChange={e=>setChoice(e.target.value)}><option value="">בחרו אפשרות</option>{variants.map(v=><option key={v.name} value={v.name} disabled={v.stock<1}>{v.name}{v.stock<1?' — אזל':''}</option>)}</select></label>}<span className="stock-label">{product.stock>0?'קיים במלאי':'אזל מהמלאי'}</span><button className="button dark wide" disabled={preview||!product.stock||(variants.length>0&&!choice)} onClick={()=>add({...product,selected_variant:choice})}>{preview?'תצוגה לדוגמה':'הוספה לסל'} <Arrow/></button><small>פרטי משלוח ותשלום יוצגו לאחר חיבור ספק הסליקה של החנויות.</small></div></div></main>}
function Empty({text}:{text:string}) {return <div className="empty"><span aria-hidden="true">✳</span><p>{text}</p></div>}
function Missing(){return <main className="wrap inner-page"><h1>העמוד לא נמצא.</h1><Link className="button dark" to="/">חזרה לדף הבית <Arrow/></Link></main>}
const cartKey=(p:Product)=>p.id+':'+(p.selected_variant||'')
function Cart({items,setItems,close,preview}:{items:Array<{product:Product,quantity:number}>;setItems:(items:Array<{product:Product,quantity:number}>)=>void;close:()=>void;preview:boolean}) {
  const closeRef=useRef<HTMLButtonElement>(null)
  useEffect(()=>{const previous=document.body.style.overflow;document.body.style.overflow='hidden';closeRef.current?.focus();const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')close()};window.addEventListener('keydown',onKey);return()=>{document.body.style.overflow=previous;window.removeEventListener('keydown',onKey)}},[])
  const total=items.reduce((sum,item)=>sum+item.product.price_agorot*item.quantity,0)
  const change=(id:string,delta:number)=>setItems(items.map(item=>cartKey(item.product)===id?{...item,quantity:item.quantity+delta}:item).filter(item=>item.quantity>0))
  return <div className="drawer-overlay" onMouseDown={close}><aside className="cart-drawer" role="dialog" aria-modal="true" aria-label="סל הקניות" onMouseDown={e=>e.stopPropagation()}><div className="drawer-head"><div><span className="eyebrow">המוצרים שבחרתם</span><h2>הסל שלי</h2></div><button ref={closeRef} className="icon-button" onClick={close} aria-label="סגירת הסל"><Icon name="close"/></button></div>{items.length?<><div className="cart-list">{items.map(({product,quantity})=><div className="cart-row" key={cartKey(product)}><Art product={product}/><div><strong>{product.name}</strong><small>{product.store_name}{product.selected_variant?' · '+product.selected_variant:''}</small><div className="qty"><button onClick={()=>change(cartKey(product),-1)} aria-label="הפחתת כמות">−</button><span>{quantity}</span><button onClick={()=>change(cartKey(product),1)} disabled={quantity>=product.stock} aria-label="הגדלת כמות">+</button></div></div><b>{ils(product.price_agorot*quantity)}</b></div>)}</div><div className="cart-bottom"><div className="total"><span>סך הכול</span><strong>{ils(total)}</strong></div><p>התשלום ייפתח לאחר חיבור ספק סליקה לחנויות. לא בוצע חיוב או הזמנה.</p><button className="button dark wide" disabled>המשך לתשלום</button></div></>:<div className="empty-cart"><span aria-hidden="true">✳</span><h3>עדיין שקט כאן</h3><p>מוצרים שתבחרו יופיעו בסל שלכם.</p><button className="button dark" onClick={close}>להמשיך לגלות</button></div>}{preview&&<span className="sr-only">קטלוג לדוגמה</span>}</aside></div>
}
function Business(){return <main><section className="business-hero"><div className="wrap"><span className="eyebrow">מדרום לעסקים</span><h1>לחנות שלכם יש<br/><em>עוד מקום לצמוח.</em></h1><p>חלון ראווה דיגיטלי, מוצרים במקום אחד וסביבת ניהול שמרכזת את העבודה.</p><Link className="button light" to="/login">כניסה למערכת <Arrow/></Link></div></section><section className="section wrap"><div className="section-heading"><div><span className="eyebrow">בדרך שלכם</span><h2>מה אפשר לעשות במדרום?</h2></div></div><div className="feature-grid"><article><span>01</span><h3>חנות משלכם</h3><p>עמוד לעסק וקטלוג מוצרים עם מלאי ואפשרויות.</p></article><article><span>02</span><h3>הכול במקום אחד</h3><p>מוצרים, פרטי עסק והזמנות בסביבת ניהול אחת.</p></article><article><span>03</span><h3>כסף ברור</h3><p>תנועות, חשבוניות ותשלומים לאחר חיבור הספקים המתאימים.</p></article></div></section></main>}
function Info({kind}:{kind:'privacy'|'accessibility'}){return <main className="wrap inner-page prose"><span className="eyebrow">מידע</span><h1>{kind==='privacy'?'פרטיות':'נגישות'}</h1>{kind==='privacy'?<><p>בשלב זה הסל נשמר רק בזיכרון הדף ונמחק ברענון. לאחר הפעלת המערכת, פרטי חשבון ונתוני הזמנות יישמרו לצורך מתן השירות ויוצגו רק לבעלי הרשאות מתאימות.</p><p>אין להזין פרטי תשלום באתר עד שיופעל ספק סליקה מאושר. מדיניות פרטיות מלאה תפורסם לפני הפעלת קניות.</p></>:<><p>האתר נבנה לקריאה מימין לשמאל, ניווט במקלדת, תוויות ברורות ושינוי גודל טקסט באמצעות הדפדפן.</p><p>אם נתקלתם בקושי שימוש, פנו למפעילי האתר כדי שנוכל לתקן אותו.</p></>}</main>}
function Login({setUser}:{setUser:(user:Account)=>void}) {const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[errorText,setError]=useState(''),[busy,setBusy]=useState(false),navigate=useNavigate()
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const data=await send<{user:Account}>('/login','POST',{email,password});setUser(data.user);navigate(data.user.role==='admin'?'/admin':'/merchant')}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
  return <main className="login-wrap"><div className="login-card"><span className="eyebrow">העסק שלכם, בידיים שלכם</span><h1>טוב שחזרתם<span className="dot">.</span></h1><p>היכנסו לניהול החנות שלכם במדרום.</p><form onSubmit={submit} className="stack"><label className="field">כתובת מייל<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="field">סיסמה<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{errorText&&<p className="form-error" role="alert">{errorText}</p>}<button className="button dark wide" disabled={busy}>{busy?'מתחברים…':'כניסה למערכת'} <Arrow/></button></form><small>חשבון סוחר נפתח על ידי מנהל המערכת.</small></div></main>
}
function Panel({title,children,action}:{title:string;children:ReactNode;action?:ReactNode}){return <section className="panel"><div className="panel-heading"><h2>{title}</h2>{action}</div>{children}</section>}
const statusLabel:Record<string,string>={draft:'טיוטה',active:'פעיל',paused:'מושהה',archived:'בארכיון',new:'חדשה',confirmed:'אושרה',preparing:'בהכנה',ready:'מוכנה',shipped:'נשלחה',delivered:'נמסרה',cancelled:'בוטלה'}
function Metric({label,value}:{label:string;value:string|number}){return <div className="metric"><small>{label}</small><strong>{value}</strong></div>}
function Admin({user,onLogout}:{user:Account|null;onLogout:()=>void}){const [data,setData]=useState<AdminData|null>(null),[errorText,setError]=useState(''),[notice,setNotice]=useState(''),[form,setForm]=useState({name:'',category:'',city:'',email:'',password:''})
  const reload=()=>api<AdminData>('/admin/overview').then(setData).catch(e=>setError(e.message))
  useEffect(()=>{if(user?.role==='admin')reload()},[user])
  if(!user)return <Gate/>;if(user.role!=='admin')return <Missing/>
  async function add(e:FormEvent){e.preventDefault();setError('');try{await send('/admin/stores','POST',form);setForm({name:'',category:'',city:'',email:'',password:''});setNotice('החנות נוצרה כטיוטה. פרטי הכניסה הוגדרו לסוחר.');reload()}catch(e){setError((e as Error).message)}}
  async function change(s:Store,status:string){try{await send(`/admin/stores/${s.id}/status`,'PATCH',{status});reload()}catch(e){setError((e as Error).message)}}
  return <main className="dashboard wrap"><div className="dashboard-top"><div><span className="eyebrow">ניהול הפלטפורמה</span><h1>שלום, {user.name}<span className="dot">.</span></h1><p>החנויות וההרשאות במדרום.</p></div><button className="text-button" onClick={onLogout}>יציאה</button></div>{errorText&&<p className="form-error" role="alert">{errorText}</p>}{notice&&<p className="form-success" role="status">{notice}</p>}<div className="metrics"><Metric label="חנויות" value={data?.stores.length??'–'}/><Metric label="חנויות פעילות" value={data?.stores.filter(s=>s.status==='active').length??'–'}/><Metric label="חשבונות סוחר" value={data?.users.length??'–'}/></div><div className="dashboard-grid"><Panel title="חנויות במערכת">{data?.stores.length?<div className="list">{data.stores.map(s=><div className="list-row" key={s.id}><div><strong>{s.name}</strong><small>{s.category} · {s.product_count} מוצרים · {statusLabel[s.status||'draft']}</small></div><select aria-label={`סטטוס ${s.name}`} value={s.status} onChange={e=>change(s,e.target.value)}><option value="draft">טיוטה</option><option value="active">פעיל</option><option value="paused">מושהה</option></select></div>)}</div>:<Empty text="עדיין לא נוספו חנויות."/>}</Panel><Panel title="הוספת חנות"><form className="stack" onSubmit={add}><label className="field">שם החנות<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="two-fields"><label className="field">קטגוריה<input required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label className="field">עיר<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label></div><label className="field">מייל לסוחר<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="field">סיסמה ראשונית, 12 תווים לפחות<input required type="password" minLength={12} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><button className="button dark">יצירת חנות <Arrow/></button></form></Panel></div></main>
}
function Gate(){return <main className="wrap inner-page"><h1>כניסה לאזור הניהול</h1><p>יש להתחבר כדי להמשיך.</p><Link to="/login" className="button dark">לכניסה <Arrow/></Link></main>}
function Merchant({user,onLogout}:{user:Account|null;onLogout:()=>void}){const [data,setData]=useState<MerchantData|null>(null),[errorText,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState('overview'),[editing,setEditing]=useState<Product|null>(null)
  const reload=()=>api<MerchantData>('/merchant/overview').then(setData).catch(e=>setError(e.message))
  useEffect(()=>{if(user?.role==='merchant')reload()},[user])
  if(!user)return <Gate/>;if(user.role!=='merchant')return <Missing/>
  async function saveProduct(values:Record<string,unknown>){setError('');try{await send(editing?`/merchant/products/${editing.id}`:'/merchant/products',editing?'PATCH':'POST',values);setEditing(null);setNotice('המוצר נשמר בהצלחה');reload()}catch(e){setError((e as Error).message)}}
  async function archive(p:Product){if(!window.confirm(`להעביר את ${p.name} לארכיון?`))return;try{await send(`/merchant/products/${p.id}`,'DELETE');reload()}catch(e){setError((e as Error).message)}}
  async function updateStatus(o:Order,status:string){try{await send(`/merchant/orders/${o.id}/status`,'PATCH',{status});reload()}catch(e){setError((e as Error).message)}}
  async function saveProfile(values:Record<string,string>){try{await send('/merchant/profile','PATCH',values);setNotice('פרטי העסק נשמרו');reload()}catch(e){setError((e as Error).message)}}
  const balance=data?.ledger.reduce((sum,e)=>sum+e.amount_agorot,0)||0
  return <main className="dashboard wrap"><div className="dashboard-top"><div><span className="eyebrow">סביבת העסק</span><h1>בוקר טוב, {user.name}<span className="dot">.</span></h1><p>{data?.store?.name||'החנות שלכם'} · מקום אחד לניהול העסק</p></div><button className="text-button" onClick={onLogout}>יציאה</button></div>{errorText&&<p className="form-error" role="alert">{errorText}</p>}{notice&&<p className="form-success" role="status">{notice}</p>}<div className="dash-tabs" role="tablist" aria-label="אזורי ניהול">{[['overview','סקירה'],['products','מוצרים'],['orders','הזמנות'],['finance','כספים'],['settings','פרטי העסק']].map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
    {tab==='overview'&&<><div className="metrics"><Metric label="מוצרים פעילים" value={data?.products.filter(p=>p.status==='active').length??'–'}/><Metric label="הזמנות ששולמו" value={data?.orders.filter(o=>o.payment_status==='paid').length??'–'}/><Metric label="יתרת תנועות" value={ils(balance)}/></div><div className="dashboard-grid"><Panel title="הצעדים להפעלת החנות"><div className="checklist"><span className={data?.profile?.status==='submitted'?'done':''}>01 <strong>ממלאים פרטי עסק</strong></span><span className={data?.products.length?'done':''}>02 <strong>מוסיפים מוצרים</strong></span><span>03 <strong>מחברים סליקה וחשבוניות</strong></span><span>04 <strong>מנהל המערכת מפעיל את החנות</strong></span></div></Panel><Panel title="המצב כרגע"><p className="muted">סטטוס החנות: <b>{statusLabel[data?.store?.status||'draft']}</b></p><p className="muted">סליקה: <b>{data?.payment?.charges_enabled?'מחוברת':'ממתינה לחיבור'}</b></p><p className="muted">חשבוניות: <b>{data?.invoice?.connection_status==='connected'?'מחוברות':'ממתינות לחיבור'}</b></p><p className="muted">קבלת תשלום תתאפשר לאחר חיבור ספק סליקה וחשבוניות מתאים.</p></Panel></div></>}
    {tab==='products'&&<div className="dashboard-grid"><Panel title={editing?'עריכת מוצר':'מוצר חדש'}><ProductForm key={editing?.id||'new'} product={editing} save={saveProduct} cancel={()=>setEditing(null)}/></Panel><Panel title="המוצרים שלכם">{data?.products.length?<div className="list">{data.products.filter(p=>p.status!=='archived').map(p=><div className="list-row" key={p.id}><div><strong>{p.name}</strong><small>{ils(p.price_agorot)} · {p.stock} במלאי · {statusLabel[p.status||'draft']}</small></div><div className="row-actions"><button onClick={()=>setEditing(p)}>עריכה</button><button onClick={()=>archive(p)}>ארכיון</button></div></div>)}</div>:<Empty text="עוד לא נוספו מוצרים. הוסיפו את הראשון שלכם."/>}</Panel></div>}
    {tab==='orders'&&<Panel title="הזמנות">{data?.orders.length?<div className="list">{data.orders.map(o=><div className="list-row" key={o.id}><div><strong>#{o.id.slice(0,8)} · {o.customer_name}</strong><small>{ils(o.total_agorot)} · {new Date(o.created_at+'Z').toLocaleDateString('he-IL')} · {statusLabel[o.fulfillment_status]||o.fulfillment_status}</small></div><select aria-label="עדכון סטטוס הזמנה" value={o.fulfillment_status} onChange={e=>updateStatus(o,e.target.value)} disabled={o.payment_status!=='paid'}>{[o.fulfillment_status,...({new:['confirmed','cancelled'],confirmed:['preparing','cancelled'],preparing:['ready'],ready:['shipped','delivered'],shipped:['delivered']} as Record<string,string[]>)[o.fulfillment_status]||[]].map(s=><option key={s} value={s}>{statusLabel[s]||s}</option>)}</select></div>)}</div>:<Empty text="אין הזמנות כרגע. הזמנות ששולמו יופיעו כאן."/>}</Panel>}
    {tab==='finance'&&<><div className="metrics"><Metric label="יתרת תנועות" value={ils(balance)}/><Metric label="מצב חשבון תשלום" value={data?.payment?.charges_enabled?'פעיל':'טרם חובר'}/><Metric label="חשבוניות" value={data?.invoice?.connection_status==='connected'?'מחובר':'טרם חובר'}/></div><Panel title="תנועות כספיות"><p className="muted">כל תנועה נשמרת כרשומה נפרדת. הנתונים יופיעו לאחר חיבור הסליקה.</p>{data?.ledger.length?<div className="list">{data.ledger.map((entry:Entry)=><div className="list-row" key={entry.id}><div><strong>{entry.kind}</strong><small>{entry.created_at}</small></div><b>{ils(entry.amount_agorot)}</b></div>)}</div>:<Empty text="אין תנועות להצגה."/>}</Panel></>}
    {tab==='settings'&&<Panel title="פרטי העסק"><ProfileForm key={data?.profile?.legal_name||'empty'} store={data?.store} profile={data?.profile} save={saveProfile}/></Panel>}
  </main>
}
function ProductForm({product,save,cancel}:{product:Product|null;save:(v:Record<string,unknown>)=>void;cancel:()=>void}) {
  const [form,setForm]=useState({name:product?.name||'',category:product?.category||'',description:product?.description||'',price:String((product?.price_agorot||0)/100||''),stock:String(product?.stock??''),image_url:product?.image_url||'',status:product?.status||'draft',variants:product?.variants_json==='[]'?'':(JSON.parse(product?.variants_json||'[]') as Array<{name:string,stock:number}>).map(v=>`${v.name}:${v.stock}`).join(', ')})
  const [localError,setLocalError]=useState('')
  function submit(e:FormEvent){e.preventDefault();const variantInput=form.variants.split(',').map(v=>v.trim()).filter(Boolean);const variants=variantInput.map(v=>{const [name,stock]=v.split(':');return {name:name?.trim(),stock:Number(stock)}});if(variants.some(v=>!v.name||!Number.isSafeInteger(v.stock)||v.stock<0)){setLocalError('אפשרויות המוצר צריכות להיות בפורמט: צבע:5, מידה:3');return}save({...form,price_agorot:Math.round(Number(form.price)*100),stock:Number(form.stock),variants})}
  return <form className="stack" onSubmit={submit}><label className="field">שם המוצר<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="two-fields"><label className="field">קטגוריה<input required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label className="field">מחיר בש״ח<input type="number" min="0" step=".01" required value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label></div><div className="two-fields"><label className="field">כמות במלאי<input type="number" min="0" required value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/></label><label className="field">פרסום<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">טיוטה</option><option value="active">פרסום</option></select></label></div><label className="field">תיאור<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="field">כתובת תמונה מאובטחת<input type="url" placeholder="https://" value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})}/></label><label className="field">אפשרויות ומלאי, לדוגמה שחור:5, לבן:3<input value={form.variants} onChange={e=>setForm({...form,variants:e.target.value})}/></label>{localError&&<p className="form-error" role="alert">{localError}</p>}<div className="form-actions"><button className="button dark">שמירת מוצר</button>{product&&<button type="button" className="text-button" onClick={cancel}>ביטול עריכה</button>}</div></form>
}
function ProfileForm({store,profile,save}:{store?:Store;profile:Record<string,string>|null|undefined;save:(v:Record<string,string>)=>void}) {
  const [form,setForm]=useState({store_name:store?.name||'',description:store?.description||'',city:store?.city||'',legal_name:profile?.legal_name||'',entity_type:profile?.entity_type||'',registration_number:profile?.registration_number||'',contact_email:profile?.contact_email||'',contact_phone:profile?.contact_phone||''})
  return <form className="stack profile-form" onSubmit={e=>{e.preventDefault();save(form)}}><div className="two-fields"><label className="field">שם החנות<input required value={form.store_name} onChange={e=>setForm({...form,store_name:e.target.value})}/></label><label className="field">עיר<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label></div><label className="field">תיאור החנות<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="two-fields"><label className="field">שם משפטי<input required value={form.legal_name} onChange={e=>setForm({...form,legal_name:e.target.value})}/></label><label className="field">סוג ישות<input placeholder="עוסק / חברה / עמותה" value={form.entity_type} onChange={e=>setForm({...form,entity_type:e.target.value})}/></label></div><div className="two-fields"><label className="field">מספר רישום<input value={form.registration_number} onChange={e=>setForm({...form,registration_number:e.target.value})}/></label><label className="field">טלפון עסקי<input type="tel" value={form.contact_phone} onChange={e=>setForm({...form,contact_phone:e.target.value})}/></label></div><label className="field">מייל עסקי<input type="email" required value={form.contact_email} onChange={e=>setForm({...form,contact_email:e.target.value})}/></label><button className="button dark">שמירת פרטי העסק</button></form>
}
export default function App() {
  const location=useLocation()
  const [catalog,setCatalog]=useState<{stores:Store[];products:Product[]}|null>(null),[preview,setPreview]=useState(false)
  const [user,setUser]=useState<Account|null>(null),[cart,setCart]=useState<Array<{product:Product;quantity:number}>>([]),[cartOpen,setCartOpen]=useState(false)
  useEffect(()=>{api<{stores:Store[];products:Product[]}>('/catalog').then(data=>{setCatalog(data.stores.length||data.products.length?data:{stores:exampleStores,products:exampleProducts});setPreview(!data.stores.length&&!data.products.length)}).catch(()=>{setCatalog({stores:exampleStores,products:exampleProducts});setPreview(true)});api<{user:Account|null}>('/session').then(d=>setUser(d.user)).catch(()=>{})},[])
  useEffect(()=>{const path=location.pathname;const product=catalog?.products.find(p=>path===`/product/${p.id}`);const store=catalog?.stores.find(s=>path===`/store/${s.slug}`);const section=product?.name||store?.name||({'/catalog':'כל המוצרים','/stores':'חנויות','/for-business':'מדרום לעסקים','/merchant':'אזור העסק','/admin':'ניהול הפלטפורמה'} as Record<string,string>)[path];document.title=section?`${section} | מדרום`:'מדרום | קונים קרוב, מגלים יותר';const desc=document.querySelector('meta[name="description"]');desc?.setAttribute('content',product?.description||store?.description||'מדרום — חנויות מקומיות ומוצרים שווים, במקום אחד.');let robots=document.querySelector('meta[name="robots"]');if(!robots){robots=document.createElement('meta');robots.setAttribute('name','robots');document.head.append(robots)}robots.setAttribute('content',/^\/(admin|merchant|login)/.test(path)?'noindex,nofollow':'index,follow')},[location.pathname,catalog])
  function add(product:Product){const variant=JSON.parse(product.variants_json||'[]') as Array<{name:string,stock:number}>;const max=product.selected_variant?Math.min(product.stock,variant.find(v=>v.name===product.selected_variant)?.stock??0):product.stock;if(max<1)return;setCart(items=>{const existing=items.find(i=>cartKey(i.product)===cartKey(product));return existing?items.map(i=>cartKey(i.product)===cartKey(product)?{...i,quantity:Math.min(max,i.quantity+1)}:i):[...items,{product:{...product,stock:max},quantity:1}]});setCartOpen(true)}
  async function logout(){await send('/logout','POST').catch(()=>{});setUser(null)}
  const stores=catalog?.stores||[],products=catalog?.products||[]
  return <><a className="skip-link" href="#main">דילוג לתוכן הראשי</a><Header count={cart.reduce((a,b)=>a+b.quantity,0)} user={user} onCart={()=>setCartOpen(true)}/><div id="main" tabIndex={-1}><Routes><Route path="/" element={<Home stores={stores} products={products} preview={preview} add={add}/>}/><Route path="/catalog" element={<Catalog products={products} preview={preview} add={add}/>}/><Route path="/stores" element={<Stores stores={stores} preview={preview}/>}/><Route path="/store/:slug" element={<StorePage stores={stores} products={products} preview={preview} add={add}/>}/><Route path="/product/:id" element={<ProductPage products={products} preview={preview} add={add}/>}/><Route path="/for-business" element={<Business/>}/><Route path="/login" element={<Login setUser={setUser}/>}/><Route path="/merchant" element={<Merchant user={user} onLogout={logout}/>}/><Route path="/admin" element={<Admin user={user} onLogout={logout}/>}/><Route path="/privacy" element={<Info kind="privacy"/>}/><Route path="/accessibility" element={<Info kind="accessibility"/>}/><Route path="*" element={<Missing/>}/></Routes></div><Footer/>{cartOpen&&<Cart items={cart} setItems={setCart} close={()=>setCartOpen(false)} preview={preview}/>}</>
}
