import { useEffect, useMemo, useRef, useState, type FormEvent, type ReactNode } from 'react'
import { Link, NavLink, Navigate, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import { api, ils, send, type Account, type AdminData, type AuthCapabilities, type Entry, type MerchantData, type Order, type Product, type Store } from './api'
import CheckoutPage from './CheckoutPage'
import CustomerAccountPage from './CustomerAccountPage'
import PhoneVerification from './PhoneVerification'
import NotificationCenter from './NotificationCenter'

const Arrow = () => <span aria-hidden="true">←</span>
const Icon = ({name}:{name:'bag'|'search'|'menu'|'close'}) => <svg className="icon" aria-hidden="true" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">{name==='bag'?<><path d="M5 7h14l1 14H4L5 7Z"/><path d="M9 8V6a3 3 0 0 1 6 0v2"/></>:name==='search'?<><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 4 4"/></>:name==='menu'?<path d="M4 6h16M4 12h16M4 18h16"/>:<path d="m5 5 14 14M19 5 5 19"/>}</svg>
const initials = (name:string) => name.trim().slice(0,2)
function Art({product,large=false}:{product?:Product;large?:boolean}) {
  const [broken,setBroken]=useState(false)
  return <div className={`product-art ${large?'large':''}`}>
    {product?.image_url && !broken ? <img src={product.image_url} alt={product.name} loading="lazy" onError={()=>setBroken(true)} /> :
      <span className="photo-unavailable">תמונה תתווסף בקרוב</span>}
  </div>
}
const personalPath=(user:Account|null)=>user?.role==='admin'?'/admin':user?.role==='merchant'?'/merchant':user?'/account':'/login'
function Header({count,user,onCart}:{count:number;user:Account|null;onCart:()=>void}) {
  const [menu,setMenu]=useState(false)
  return <>
    <div className="announcement">מוצרים וחנויות במקום אחד · בוחרים את מה שאוהבים</div>
    <header className="site-header"><div className="header-inner">
      <Link to="/" className="brand" aria-label="מדרום, לדף הבית"><span className="brand-symbol">מ</span><span>מדרום<small>החנות שלכם</small></span></Link>
      <nav className={menu?'nav open':'nav'} aria-label="ניווט ראשי" onClick={()=>setMenu(false)}>
        <NavLink to="/" end>בית</NavLink><NavLink to="/catalog">מוצרים</NavLink><NavLink to="/stores">חנויות</NavLink>
        <NavLink className="mobile-only" to={personalPath(user)}>האזור האישי</NavLink>
      </nav>
      <div className="header-actions">
        {user&&<NotificationCenter user={user}/>}
        <Link className="quiet-action desktop-only" to={personalPath(user)}>{user?`שלום, ${user.name}`:'כניסה והרשמה'}</Link>
        <button className="icon-button cart-trigger" type="button" aria-label={`פתיחת הסל, ${count} פריטים`} onClick={onCart}><Icon name="bag"/>{count>0&&<span className="cart-count">{count}</span>}</button>
        <button className="icon-button mobile-only" type="button" aria-label={menu?'סגירת תפריט':'פתיחת תפריט'} aria-expanded={menu} onClick={()=>setMenu(!menu)}><Icon name={menu?'close':'menu'}/></button>
      </div>
    </div></header>
  </>
}
function Footer() {return <footer className="site-footer"><div className="wrap footer-grid"><div><Link className="brand" to="/"><span className="brand-symbol">מ</span><span>מדרום<small>החנות שלכם</small></span></Link><p>מוצרים מהחנויות במדרום, במקום אחד.</p></div><div><strong>קניות</strong><Link to="/catalog">כל המוצרים</Link><Link to="/stores">החנויות</Link></div><div><strong>החשבון</strong><Link to="/login">כניסה והרשמה</Link></div><div><strong>מידע</strong><Link to="/privacy">פרטיות</Link><Link to="/accessibility">נגישות</Link></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} מדרום</span><span>קונים קרוב, בוחרים טוב</span></div></footer>}
function StoreCard({store,index}:{store:Store;index:number}) {
  return <Link to={`/store/${store.slug}`} className={`store-tile store-tone-${index%3}`}>
    {store.logo_url?<img className="store-logo" src={store.logo_url} alt="" loading="lazy"/>:<span className="store-monogram" aria-hidden="true">{initials(store.name)}</span>}
    <span className="store-tile-copy"><small>{store.category}</small><strong>{store.name}</strong><span>{store.city||'לגלות את החנות'}</span></span><Arrow/>
  </Link>
}
function ProductCard({product,add}:{product:Product;add:(product:Product)=>void}) {
  let hasVariants=false;try{hasVariants=(JSON.parse(product.variants_json||'[]') as unknown[]).length>0}catch{}
  return <article className="product-card"><Link to={`/product/${product.id}`} aria-label={`פרטי ${product.name}`}><Art product={product}/></Link><div className="product-meta"><Link to={`/store/${product.store_slug}`} className="store-label">{product.store_name}</Link><Link className="product-title" to={`/product/${product.id}`}>{product.name}</Link><div className="price-line"><strong>{ils(product.price_agorot)}</strong>{hasVariants?<Link className="round-add" to={`/product/${product.id}`} aria-label={`בחירת אפשרות ל${product.name}`}>←</Link>:<button type="button" className="round-add" disabled={product.stock<1} onClick={()=>add(product)} aria-label={`הוספת ${product.name} לסל`}>+</button>}</div>{product.stock<1&&<small>אזל מהמלאי</small>}</div></article>
}
function Home({stores,products,add}:{stores:Store[];products:Product[];add:(product:Product)=>void}) {
  return <main>
    <section className="hero"><div className="wrap hero-layout"><div className="hero-content"><span className="eyebrow">ברוכים הבאים למדרום</span><h1>למצוא משהו<br/><em>בדיוק בשבילכם.</em></h1><p>מוצרים מחנויות שונות במקום אחד. מחפשים, בוחרים ומכירים את החנות שמאחורי כל פריט.</p><div className="hero-actions"><Link className="button dark" to="/catalog">לכל המוצרים <Arrow/></Link><Link className="text-button" to="/stores">לחנויות <Arrow/></Link></div></div><div className="hero-photo"><img src="/shop-hero.jpg" alt="מדפים ותצוגת מוצרים בחנות" fetchPriority="high"/></div></div></section>
    <section className="value-strip"><div className="wrap value-grid"><span>01 <strong>מגלים מוצרים</strong></span><span>02 <strong>בוחרים מהסל</strong></span><span>03 <strong>שומרים על קשר עם החנות</strong></span></div></section>
    <section className="section wrap"><div className="section-heading"><div><span className="eyebrow">לגלות עוד</span><h2>החנויות במדרום<span className="dot">.</span></h2></div><Link className="text-button" to="/stores">לכל החנויות <Arrow/></Link></div>{stores.length?<div className="store-grid">{stores.slice(0,4).map((store,index)=><StoreCard key={store.id} store={store} index={index}/>)}</div>:<Empty text="החנויות הראשונות יופיעו כאן כשיפתחו לקנייה."/>}</section>
    <section className="section products-section"><div className="wrap"><div className="section-heading"><div><span className="eyebrow">מה חדש</span><h2>מוצרים בחנויות<span className="dot">.</span></h2></div><Link className="text-button" to="/catalog">לכל המוצרים <Arrow/></Link></div>{products.length?<div className="product-grid">{products.slice(0,8).map(p=><ProductCard key={p.id} product={p} add={add}/>)}</div>:<Empty text="מוצרים חדשים יופיעו כאן לאחר שהחנויות יפרסמו אותם."/>}</div></section>
  </main>
}
function Catalog({products,add}:{products:Product[];add:(p:Product)=>void}) {
  const [search,setSearch]=useState(''),[category,setCategory]=useState('הכול'),[sort,setSort]=useState('new')
  const categories=['הכול',...new Set(products.map(p=>p.category).filter(Boolean))]
  const filtered=useMemo(()=>products.filter(p=>(category==='הכול'||p.category===category)&&(`${p.name} ${p.store_name} ${p.description}`).toLocaleLowerCase('he').includes(search.toLocaleLowerCase('he'))).sort((a,b)=>sort==='low'?a.price_agorot-b.price_agorot:sort==='high'?b.price_agorot-a.price_agorot:0),[products,search,category,sort])
  return <main className="wrap inner-page"><div className="page-intro"><span className="eyebrow">למצוא את הדבר הבא</span><h1>כל המוצרים<span className="dot">.</span></h1><p>חפשו לפי שם, חנות או קטגוריה.</p></div><div className="catalog-tools"><label className="search-field"><span className="sr-only">חיפוש מוצרים וחנויות</span><Icon name="search"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="מה מחפשים היום?"/></label><label className="sort-field">מיון <select value={sort} onChange={e=>setSort(e.target.value)}><option value="new">הכי חדשים</option><option value="low">מחיר מהנמוך</option><option value="high">מחיר מהגבוה</option></select></label></div><div className="chips" aria-label="סינון לפי קטגוריה">{categories.map(c=><button type="button" key={c} aria-pressed={category===c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><p className="result-count" role="status">{filtered.length} מוצרים</p>{filtered.length?<div className="product-grid">{filtered.map(p=><ProductCard key={p.id} product={p} add={add}/>)}</div>:<Empty text={products.length?'לא נמצאו מוצרים. נסו חיפוש אחר.':'מוצרים יופיעו כאן לאחר שיפורסמו בחנויות.'}/>}</main>
}
function Stores({stores}:{stores:Store[]}) {return <main className="wrap inner-page"><div className="page-intro"><span className="eyebrow">בחנות שלכם</span><h1>כל החנויות<span className="dot">.</span></h1><p>הכירו את החנויות והמוצרים שלהן.</p></div>{stores.length?<div className="store-grid">{stores.map((store,index)=><StoreCard key={store.id} store={store} index={index}/>)}</div>:<Empty text="החנויות הראשונות יופיעו כאן בקרוב."/>}</main>}
function StorePage({stores,products,add}:{stores:Store[];products:Product[];add:(p:Product)=>void}) {const {slug}=useParams(),store=stores.find(s=>s.slug===slug);if(!store)return <Missing/>;const items=products.filter(p=>p.store_id===store.id);return <main><section className="store-hero"><div className="wrap"><Link to="/stores" className="back-link">לכל החנויות <Arrow/></Link><div className="store-title">{store.logo_url?<img className="store-logo" src={store.logo_url} alt=""/>:<span className="store-monogram" aria-hidden="true">{initials(store.name)}</span>}<div><span className="eyebrow">{store.category} · {store.city||'מדרום'}</span><h1>{store.name}</h1><p>{store.description}</p></div></div></div></section><div className="wrap section"><h2>מוצרים בחנות<span className="dot">.</span></h2><div className="product-grid">{items.map(p=><ProductCard key={p.id} product={p} add={add}/>)}</div>{!items.length&&<Empty text="עדיין אין מוצרים בחנות הזו."/>}</div></main>}
function ProductPage({products,add}:{products:Product[];add:(p:Product)=>void}) {const {id}=useParams(),[choice,setChoice]=useState(''),product=products.find(p=>p.id===id);if(!product)return <Missing/>;let variants:Array<{name:string,stock:number}>=[];try {variants=JSON.parse(product.variants_json||'[]')}catch{}return <main className="wrap inner-page"><Link className="back-link" to="/catalog">בחזרה למוצרים <Arrow/></Link><div className="detail-grid"><Art product={product} large/><div className="detail-copy"><Link to={`/store/${product.store_slug}`} className="eyebrow">{product.store_name}</Link><h1>{product.name}</h1><strong className="detail-price">{ils(product.price_agorot)}</strong><p>{product.description||'פרטים נוספים על המוצר יתווספו בקרוב.'}</p>{variants.length>0&&<label className="field">בחירת אפשרות<select value={choice} onChange={e=>setChoice(e.target.value)}><option value="">בחרו אפשרות</option>{variants.map(v=><option key={v.name} value={v.name} disabled={v.stock<1}>{v.name}{v.stock<1?' — אזל':''}</option>)}</select></label>}<span className="stock-label">{product.stock>0?'קיים במלאי':'אזל מהמלאי'}</span><button className="button dark wide" disabled={!product.stock||(variants.length>0&&!choice)} onClick={()=>add({...product,selected_variant:choice})}>הוספה לסל <Arrow/></button><small>פרטי אספקה ותשלום יתואמו עם החנות עד להפעלת התשלום באתר.</small></div></div></main>}
function Empty({text}:{text:string}) {return <div className="empty"><span aria-hidden="true">✳</span><p>{text}</p></div>}
function Missing(){return <main className="wrap inner-page"><h1>העמוד לא נמצא.</h1><Link className="button dark" to="/">חזרה לדף הבית <Arrow/></Link></main>}
const cartKey=(p:Product)=>p.id+':'+(p.selected_variant||'')
function Cart({items,setItems,close}:{items:Array<{product:Product,quantity:number}>;setItems:(items:Array<{product:Product,quantity:number}>)=>void;close:()=>void}) {
  const closeRef=useRef<HTMLButtonElement>(null)
  useEffect(()=>{const previous=document.body.style.overflow;document.body.style.overflow='hidden';closeRef.current?.focus();const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')close()};window.addEventListener('keydown',onKey);return()=>{document.body.style.overflow=previous;window.removeEventListener('keydown',onKey)}},[])
  const total=items.reduce((sum,item)=>sum+item.product.price_agorot*item.quantity,0)
  const change=(id:string,delta:number)=>setItems(items.map(item=>cartKey(item.product)===id?{...item,quantity:item.quantity+delta}:item).filter(item=>item.quantity>0))
  return <div className="drawer-overlay" onMouseDown={close}><aside className="cart-drawer" role="dialog" aria-modal="true" aria-label="סל הקניות" onMouseDown={e=>e.stopPropagation()}><div className="drawer-head"><div><span className="eyebrow">המוצרים שבחרתם</span><h2>הסל שלי</h2></div><button ref={closeRef} className="icon-button" onClick={close} aria-label="סגירת הסל"><Icon name="close"/></button></div>{items.length?<><div className="cart-list">{items.map(({product,quantity})=><div className="cart-row" key={cartKey(product)}><Art product={product}/><div><strong>{product.name}</strong><small>{product.store_name}{product.selected_variant?' · '+product.selected_variant:''}</small><div className="qty"><button onClick={()=>change(cartKey(product),-1)} aria-label="הפחתת כמות">−</button><span>{quantity}</span><button onClick={()=>change(cartKey(product),1)} disabled={quantity>=product.stock} aria-label="הגדלת כמות">+</button></div></div><b>{ils(product.price_agorot*quantity)}</b></div>)}</div><div className="cart-bottom"><div className="total"><span>מחירי מוצרים</span><strong>{ils(total)}</strong></div><p>אפשר לשלוח בקשת רכישה לחנויות. הן יתאמו איתכם תשלום ואספקה; כאן לא נגבה תשלום.</p><Link className="button dark wide" to="/checkout" onClick={close}>לפרטי הבקשה <Arrow/></Link></div></>:<div className="empty-cart"><span aria-hidden="true">✳</span><h3>עדיין שקט כאן</h3><p>מוצרים שתבחרו יופיעו בסל שלכם.</p><button className="button dark" onClick={close}>להמשיך לגלות</button></div>}</aside></div>
}
function Info({kind}:{kind:'privacy'|'accessibility'}){return <main className="wrap inner-page prose"><span className="eyebrow">מידע</span><h1>{kind==='privacy'?'פרטיות':'נגישות'}</h1>{kind==='privacy'?<><p>הסל נשמר בדפדפן שלכם. הכניסה לחשבון משתמשת בעוגייה, ופרטי החשבון ובקשות הרכישה נשמרים במערכת. פרטי הבקשה מועברים לחנויות שמהן בחרתם מוצרים לצורך טיפול בפנייה. בקשות רכישה אינן הזמנות ששולמו.</p><p>אין להזין באתר פרטי כרטיס אשראי. לפני הפעלת התשלום תפורסם מדיניות פרטיות מלאה, כולל תקופות שמירת מידע ופרטי קשר למימוש זכויות.</p></>:<><p>האתר נבנה לקריאה מימין לשמאל, ניווט במקלדת, תוויות ברורות ושינוי גודל טקסט באמצעות הדפדפן.</p><p>אם נתקלתם בקושי שימוש, פנו למפעילי האתר כדי שנוכל לתקן אותו.</p></>}</main>}
function Login({user,setUser}:{user:Account|null;setUser:(user:Account)=>void}) {
  const [cap,setCap]=useState<AuthCapabilities|null>(null),[channel,setChannel]=useState<'email'|'sms'>('email')
  const [name,setName]=useState(''),[target,setTarget]=useState(''),[code,setCode]=useState(''),[challenge,setChallenge]=useState('')
  const [password,setPassword]=useState(''),[errorText,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
  const navigate=useNavigate(),location=useLocation()
  useEffect(()=>{api<AuthCapabilities>('/auth/capabilities').then(setCap).catch(e=>setError(e.message))},[])
  useEffect(()=>{if(new URLSearchParams(location.search).has('error'))setError('הכניסה עם Google לא הושלמה. נסו קוד למייל; אפשר לחבר Google מתוך החשבון.')},[location.search])
  if(user)return <Navigate to={personalPath(user)} replace/>
  async function request(e:FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('')
    try{const response=await send<{challenge_id:string}>('/auth/request-code','POST',{channel,target,name});setChallenge(response.challenge_id);setNotice(`שלחנו קוד אל ${target.trim()}`)}
    catch(cause){setError((cause as Error).message)}finally{setBusy(false)}}
  async function verify(e:FormEvent){e.preventDefault();setBusy(true);setError('')
    try{const result=await send<{user:Account;redirect:string}>('/auth/verify-code','POST',{challenge_id:challenge,code});setUser(result.user);navigate(result.redirect,{replace:true})}
    catch(cause){setError((cause as Error).message)}finally{setBusy(false)}}
  async function legacy(e:FormEvent){e.preventDefault();setBusy(true);setError('')
    try{const result=await send<{user:Account}>('/login','POST',{email:target,password});setUser(result.user);navigate(personalPath(result.user),{replace:true})}
    catch(cause){setError((cause as Error).message)}finally{setBusy(false)}}
  return <main className="login-wrap"><div className="login-card"><span className="eyebrow">החשבון שלכם במדרום</span><h1>כניסה והרשמה<span className="dot">.</span></h1><p>נכנסים לאזור האישי עם קוד חד־פעמי או עם Google. בהרשמה הראשונה ניצור עבורכם חשבון.</p>
    <div className="auth-tabs" role="group" aria-label="בחירת דרך כניסה"><button type="button" className={channel==='email'?'active':''} onClick={()=>{setChannel('email');setTarget('');setChallenge('');setError('');setNotice('')}}>קוד למייל</button><button type="button" className={channel==='sms'?'active':''} onClick={()=>{setChannel('sms');setTarget('');setChallenge('');setError('');setNotice('')}}>קוד ב־SMS</button></div>
    {errorText&&<p className="form-error" role="alert">{errorText}</p>}{notice&&<p className="form-success" role="status">{notice}</p>}
    {!challenge?<form className="stack" onSubmit={request}>{channel==='email'&&<label className="field">שם מלא <small>נדרש בהרשמה ראשונה</small><input autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label>}{channel==='sms'&&<small>כניסה למספר שאומת בחשבון. בהרשמה ראשונה השתמשו במייל או ב־Google.</small>}<label className="field">{channel==='email'?'כתובת מייל':'מספר טלפון'}<input required type={channel==='email'?'email':'tel'} autoComplete={channel==='email'?'email':'tel'} dir="ltr" placeholder={channel==='email'?'name@example.com':'050-0000000'} value={target} onChange={e=>setTarget(e.target.value)}/></label><button className="button dark wide" disabled={busy||!cap?.[channel]}>{busy?'שולחים…':'שליחת קוד כניסה'} <Arrow/></button>{cap&&!cap[channel]&&<small role="status">{cap.setup_required?'הכניסה באמצעות קוד אינה זמינה כרגע.':'הכניסה בדרך זו אינה זמינה כרגע.'}</small>}</form>:<form className="stack" onSubmit={verify}><p>הזינו את הקוד בן שש הספרות שנשלח אליכם.</p><label className="field">קוד אימות<input required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code" dir="ltr" value={code} onChange={e=>setCode(e.target.value)}/></label><button className="button dark wide" disabled={busy}>{busy?'בודקים…':'כניסה לחשבון'} <Arrow/></button><button type="button" className="text-button" onClick={()=>{setChallenge('');setCode('');setNotice('')}}>שינוי פרטים או קבלת קוד חדש</button></form>}
    <div className="auth-divider"><span>או</span></div><a className={`google-button ${!cap?.google?'disabled':''}`} href={cap?.google?'/api/auth/google/start':'#'} onClick={e=>{if(!cap?.google)e.preventDefault()}}>המשך עם Google</a>{cap&&!cap.google&&<small>כניסה עם Google אינה זמינה כרגע.</small>}
    <details className="legacy-login"><summary>כניסה עם סיסמה קיימת</summary><form className="stack" onSubmit={legacy}><label className="field">מייל החשבון<input type="email" required autoComplete="username" dir="ltr" value={target} onChange={e=>setTarget(e.target.value)}/></label><label className="field">סיסמה<input type="password" required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="button dark wide" disabled={busy}>כניסה</button></form></details>
  </div></main>
}
function Panel({title,children,action}:{title:string;children:ReactNode;action?:ReactNode}){return <section className="panel"><div className="panel-heading"><h2>{title}</h2>{action}</div>{children}</section>}
const statusLabel:Record<string,string>={draft:'טיוטה',active:'פעיל',paused:'מושהה',archived:'בארכיון',new:'חדשה',confirmed:'אושרה',preparing:'בהכנה',ready:'מוכנה',shipped:'נשלחה',delivered:'נמסרה',cancelled:'בוטלה'}
function Metric({label,value}:{label:string;value:string|number}){return <div className="metric"><small>{label}</small><strong>{value}</strong></div>}
function Admin({user,onLogout}:{user:Account|null;onLogout:()=>void}){const [data,setData]=useState<AdminData|null>(null),[errorText,setError]=useState(''),[notice,setNotice]=useState(''),[form,setForm]=useState({name:'',category:'',city:'',email:'',password:''})
  const reload=()=>api<AdminData>('/admin/overview').then(setData).catch(e=>setError(e.message))
  useEffect(()=>{if(user?.role==='admin')reload()},[user])
  if(!user)return <Gate/>;if(user.role!=='admin')return <Navigate to={personalPath(user)} replace/>
  async function add(e:FormEvent){e.preventDefault();setError('');try{await send('/admin/stores','POST',form);setForm({name:'',category:'',city:'',email:'',password:''});setNotice('החנות נוצרה כטיוטה. פרטי הכניסה הוגדרו לסוחר.');reload()}catch(e){setError((e as Error).message)}}
  async function change(s:Store,status:string){try{await send(`/admin/stores/${s.id}/status`,'PATCH',{status});reload()}catch(e){setError((e as Error).message)}}
  return <main className="dashboard wrap"><div className="dashboard-top"><div><span className="eyebrow">ניהול הפלטפורמה</span><h1>שלום, {user.name}<span className="dot">.</span></h1><p>החנויות וההרשאות במדרום.</p></div><button className="text-button" onClick={onLogout}>יציאה</button></div>{errorText&&<p className="form-error" role="alert">{errorText}</p>}{notice&&<p className="form-success" role="status">{notice}</p>}<div className="metrics"><Metric label="חנויות" value={data?.stores.length??'–'}/><Metric label="חנויות פעילות" value={data?.stores.filter(s=>s.status==='active').length??'–'}/><Metric label="חשבונות סוחר" value={data?.users.length??'–'}/></div><div className="dashboard-grid"><Panel title="חנויות במערכת">{data?.stores.length?<div className="list">{data.stores.map(s=><div className="list-row" key={s.id}><div><strong>{s.name}</strong><small>{s.category} · {s.product_count} מוצרים · {statusLabel[s.status||'draft']}</small></div><select aria-label={`סטטוס ${s.name}`} value={s.status} onChange={e=>change(s,e.target.value)}><option value="draft">טיוטה</option><option value="active">פעיל</option><option value="paused">מושהה</option></select></div>)}</div>:<Empty text="עדיין לא נוספו חנויות."/>}</Panel><Panel title="הוספת חנות"><PhoneVerification/><form className="stack" onSubmit={add}><label className="field">שם החנות<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="two-fields"><label className="field">קטגוריה<input required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label className="field">עיר<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label></div><label className="field">מייל לסוחר<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="field">סיסמה ראשונית, 12 תווים לפחות<input required type="password" minLength={12} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><button className="button dark">יצירת חנות <Arrow/></button></form></Panel></div></main>
}
function Gate(){return <main className="wrap inner-page"><h1>כניסה לאזור האישי</h1><p>יש להתחבר כדי להמשיך.</p><Link to="/login" className="button dark">לכניסה <Arrow/></Link></main>}
function Merchant({user,onLogout}:{user:Account|null;onLogout:()=>void}){const [data,setData]=useState<MerchantData|null>(null),[errorText,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState('overview'),[editing,setEditing]=useState<Product|null>(null)
  const reload=()=>api<MerchantData>('/merchant/overview').then(setData).catch(e=>setError(e.message))
  useEffect(()=>{if(user?.role==='merchant')reload()},[user])
  if(!user)return <Gate/>;if(user.role!=='merchant')return <Navigate to={personalPath(user)} replace/>
  async function saveProduct(values:Record<string,unknown>){setError('');try{await send(editing?`/merchant/products/${editing.id}`:'/merchant/products',editing?'PATCH':'POST',values);setEditing(null);setNotice('המוצר נשמר בהצלחה');reload()}catch(e){setError((e as Error).message)}}
  async function archive(p:Product){if(!window.confirm(`להעביר את ${p.name} לארכיון?`))return;try{await send(`/merchant/products/${p.id}`,'DELETE');reload()}catch(e){setError((e as Error).message)}}
  async function updateStatus(o:Order,status:string){try{await send(`/merchant/orders/${o.id}/status`,'PATCH',{status});reload()}catch(e){setError((e as Error).message)}}
  async function updateRequest(id:string,status:string){try{await send(`/merchant/requests/${id}`,'PATCH',{status});setNotice('סטטוס הבקשה עודכן');reload()}catch(e){setError((e as Error).message)}}
  async function saveProfile(values:Record<string,string>){try{await send('/merchant/profile','PATCH',values);setNotice('פרטי העסק נשמרו');reload()}catch(e){setError((e as Error).message)}}
  const balance=data?.ledger.reduce((sum,e)=>sum+e.amount_agorot,0)||0
  return <main className="dashboard wrap"><div className="dashboard-top"><div><span className="eyebrow">סביבת העסק</span><h1>בוקר טוב, {user.name}<span className="dot">.</span></h1><p>{data?.store?.name||'החנות שלכם'} · מקום אחד לניהול העסק</p></div><button className="text-button" onClick={onLogout}>יציאה</button></div>{errorText&&<p className="form-error" role="alert">{errorText}</p>}{notice&&<p className="form-success" role="status">{notice}</p>}<div className="dash-tabs" role="tablist" aria-label="אזורי ניהול">{[['overview','סקירה'],['products','מוצרים'],['requests','בקשות רכישה'],['orders','הזמנות ששולמו'],['finance','כספים'],['settings','פרטי העסק']].map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
    {tab==='overview'&&<><div className="metrics"><Metric label="מוצרים פעילים" value={data?.products.filter(p=>p.status==='active').length??'–'}/><Metric label="הזמנות ששולמו" value={data?.orders.filter(o=>o.payment_status==='paid').length??'–'}/><Metric label="יתרת תנועות" value={ils(balance)}/></div><div className="dashboard-grid"><Panel title="הצעדים להפעלת החנות"><div className="checklist"><span className={data?.profile?.status==='submitted'?'done':''}>01 <strong>ממלאים פרטי עסק</strong></span><span className={data?.products.length?'done':''}>02 <strong>מוסיפים מוצרים</strong></span><span>03 <strong>מחברים סליקה וחשבוניות</strong></span><span>04 <strong>מנהל המערכת מפעיל את החנות</strong></span></div></Panel><Panel title="המצב כרגע"><p className="muted">סטטוס החנות: <b>{statusLabel[data?.store?.status||'draft']}</b></p><p className="muted">סליקה: <b>{data?.payment?.charges_enabled?'מחוברת':'ממתינה לחיבור'}</b></p><p className="muted">חשבוניות: <b>{data?.invoice?.connection_status==='connected'?'מחוברות':'ממתינות לחיבור'}</b></p><p className="muted">קבלת תשלום תתאפשר לאחר חיבור ספק סליקה וחשבוניות מתאים.</p></Panel></div></>}
    {tab==='products'&&<div className="dashboard-grid"><Panel title={editing?'עריכת מוצר':'מוצר חדש'}><ProductForm key={editing?.id||'new'} product={editing} save={saveProduct} cancel={()=>setEditing(null)}/></Panel><Panel title="המוצרים שלכם">{data?.products.length?<div className="list">{data.products.map(p=><div className="list-row" key={p.id}><div><strong>{p.name}</strong><small>{ils(p.price_agorot)} · {p.stock} במלאי · {statusLabel[p.status||'draft']}</small></div><div className="row-actions"><button onClick={()=>setEditing(p)}>עריכה</button>{p.status!=='archived'&&<button onClick={()=>archive(p)}>ארכיון</button>}</div></div>)}</div>:<Empty text="עוד לא נוספו מוצרים. הוסיפו את הראשון שלכם."/>}</Panel></div>}
    {tab==='requests'&&<Panel title="בקשות רכישה ללא חיוב"><p className="muted">אלו פניות מלקוחות. יש לתאם תשלום ואספקה ישירות; הן אינן הזמנות ששולמו והמלאי לא נשמר.</p>{data?.requests.length?<div className="request-list">{data.requests.map(request=><article className="request-card" key={request.id}><div className="request-head"><div><strong>#{request.request_id.slice(0,8)} · {request.customer_name}</strong><small>{new Date(request.created_at+'Z').toLocaleDateString('he-IL')} · {ils(request.subtotal_agorot)}</small></div><span className="request-badge">{{new:'חדשה',contacted:'נוצר קשר',closed:'נסגרה'}[request.status]}</span></div><div className="request-items">{request.items.map((item,i)=><span key={i}>{item.product_name}{item.variant?' · '+item.variant:''} × {item.quantity} · {ils(item.unit_price_agorot*item.quantity)}</span>)}</div><div className="request-actions"><a href={`tel:${request.customer_phone}`}>{request.customer_phone}</a><a href={`mailto:${request.customer_email}`}>{request.customer_email}</a>{request.status==='new'&&<button onClick={()=>updateRequest(request.id,'contacted')}>נוצר קשר</button>}{request.status!=='closed'&&<button onClick={()=>updateRequest(request.id,'closed')}>סגירת בקשה</button>}</div></article>)}</div>:<Empty text="אין בקשות רכישה כרגע."/>}</Panel>}
    {tab==='orders'&&<Panel title="הזמנות">{data?.orders.length?<div className="list">{data.orders.map(o=><div className="list-row" key={o.id}><div><strong>#{o.id.slice(0,8)} · {o.customer_name}</strong><small>{ils(o.total_agorot)} · {new Date(o.created_at+'Z').toLocaleDateString('he-IL')} · {statusLabel[o.fulfillment_status]||o.fulfillment_status}</small></div><select aria-label="עדכון סטטוס הזמנה" value={o.fulfillment_status} onChange={e=>updateStatus(o,e.target.value)} disabled={o.payment_status!=='paid'}>{[o.fulfillment_status,...({new:['confirmed','cancelled'],confirmed:['preparing','cancelled'],preparing:['ready'],ready:['shipped','delivered'],shipped:['delivered']} as Record<string,string[]>)[o.fulfillment_status]||[]].map(s=><option key={s} value={s}>{statusLabel[s]||s}</option>)}</select></div>)}</div>:<Empty text="אין הזמנות כרגע. הזמנות ששולמו יופיעו כאן."/>}</Panel>}
    {tab==='finance'&&<><div className="metrics"><Metric label="יתרת תנועות" value={ils(balance)}/><Metric label="מצב חשבון תשלום" value={data?.payment?.charges_enabled?'פעיל':'טרם חובר'}/><Metric label="חשבוניות" value={data?.invoice?.connection_status==='connected'?'מחובר':'טרם חובר'}/></div><Panel title="תנועות כספיות"><p className="muted">כל תנועה נשמרת כרשומה נפרדת. הנתונים יופיעו לאחר חיבור הסליקה.</p>{data?.ledger.length?<div className="list">{data.ledger.map((entry:Entry)=><div className="list-row" key={entry.id}><div><strong>{entry.kind}</strong><small>{entry.created_at}</small></div><b>{ils(entry.amount_agorot)}</b></div>)}</div>:<Empty text="אין תנועות להצגה."/>}</Panel></>}
    {tab==='settings'&&<Panel title="פרטי העסק"><PhoneVerification/><ProfileForm key={data?.profile?.legal_name||'empty'} store={data?.store} profile={data?.profile} save={saveProfile}/></Panel>}
  </main>
}
function ProductForm({product,save,cancel}:{product:Product|null;save:(v:Record<string,unknown>)=>void;cancel:()=>void}) {
  const [form,setForm]=useState({name:product?.name||'',category:product?.category||'',description:product?.description||'',price:String((product?.price_agorot||0)/100||''),stock:String(product?.stock??''),image_url:product?.image_url||'',status:product?.status==='archived'?'draft':product?.status||'draft',variants:product?.variants_json==='[]'?'':(JSON.parse(product?.variants_json||'[]') as Array<{name:string,stock:number}>).map(v=>`${v.name}:${v.stock}`).join(', ')})
  const [localError,setLocalError]=useState(''),[uploading,setUploading]=useState(false)
  async function upload(file:File){setLocalError('');if(file.size>5*1024*1024){setLocalError('התמונה גדולה מ־5MB');return}setUploading(true);try{const response=await fetch('/api/merchant/media',{method:'POST',credentials:'same-origin',headers:{'content-type':file.type},body:file});const data=await response.json();if(!response.ok)throw new Error(data.error||'העלאת התמונה נכשלה');setForm(current=>({...current,image_url:data.url}))}catch(e){setLocalError((e as Error).message)}finally{setUploading(false)}}
  function submit(e:FormEvent){e.preventDefault();const variantInput=form.variants.split(',').map(v=>v.trim()).filter(Boolean);const variants=variantInput.map(v=>{const [name,stock]=v.split(':');return {name:name?.trim(),stock:Number(stock)}});if(variants.some(v=>!v.name||!Number.isSafeInteger(v.stock)||v.stock<0)){setLocalError('אפשרויות המוצר צריכות להיות בפורמט: צבע:5, מידה:3');return}save({...form,price_agorot:Math.round(Number(form.price)*100),stock:Number(form.stock),variants})}
  return <form className="stack" onSubmit={submit}>{product?.status==='archived'&&<p className="muted">המוצר בארכיון. שמירתו כטיוטה תחזיר אותו לרשימה הפעילה.</p>}<label className="field">שם המוצר<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="two-fields"><label className="field">קטגוריה<input required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label className="field">מחיר בש״ח<input type="number" min="0" step=".01" required value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label></div><div className="two-fields"><label className="field">כמות במלאי<input type="number" min="0" required value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/></label><label className="field">פרסום<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">טיוטה</option><option value="active">פרסום</option></select></label></div><label className="field">תיאור<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="field">כתובת תמונה מאובטחת<input type="text" inputMode="url" placeholder="https://" value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})}/></label><label className="field">או העלאת תמונה (JPG, PNG, WebP עד 5MB)<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)upload(file)}}/></label>{uploading&&<p role="status">מעלים תמונה…</p>}<label className="field">אפשרויות ומלאי, לדוגמה שחור:5, לבן:3<input value={form.variants} onChange={e=>setForm({...form,variants:e.target.value})}/></label>{localError&&<p className="form-error" role="alert">{localError}</p>}<div className="form-actions"><button className="button dark" disabled={uploading}>שמירת מוצר</button>{product&&<button type="button" className="text-button" onClick={cancel}>ביטול עריכה</button>}</div></form>
}
function ProfileForm({store,profile,save}:{store?:Store;profile:Record<string,string>|null|undefined;save:(v:Record<string,string>)=>void}) {
  const [form,setForm]=useState({store_name:store?.name||'',description:store?.description||'',city:store?.city||'',legal_name:profile?.legal_name||'',entity_type:profile?.entity_type||'',registration_number:profile?.registration_number||'',contact_email:profile?.contact_email||'',contact_phone:profile?.contact_phone||''})
  return <form className="stack profile-form" onSubmit={e=>{e.preventDefault();save(form)}}><div className="two-fields"><label className="field">שם החנות<input required value={form.store_name} onChange={e=>setForm({...form,store_name:e.target.value})}/></label><label className="field">עיר<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label></div><label className="field">תיאור החנות<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="two-fields"><label className="field">שם משפטי<input required value={form.legal_name} onChange={e=>setForm({...form,legal_name:e.target.value})}/></label><label className="field">סוג ישות<input placeholder="עוסק / חברה / עמותה" value={form.entity_type} onChange={e=>setForm({...form,entity_type:e.target.value})}/></label></div><div className="two-fields"><label className="field">מספר רישום<input value={form.registration_number} onChange={e=>setForm({...form,registration_number:e.target.value})}/></label><label className="field">טלפון עסקי<input type="tel" value={form.contact_phone} onChange={e=>setForm({...form,contact_phone:e.target.value})}/></label></div><label className="field">מייל עסקי<input type="email" required value={form.contact_email} onChange={e=>setForm({...form,contact_email:e.target.value})}/></label><button className="button dark">שמירת פרטי העסק</button></form>
}
function Loading(){return <main className="wrap inner-page loading-state" role="status"><span className="loading-dot"/>טוענים את הפרטים…</main>}
export default function App() {
  const location=useLocation()
  const [catalog,setCatalog]=useState<{stores:Store[];products:Product[]}|null>(null),[catalogError,setCatalogError]=useState(''),[retry,setRetry]=useState(0)
  const [user,setUser]=useState<Account|null>(null),[sessionLoading,setSessionLoading]=useState(true)
  const [cart,setCart]=useState<Array<{product:Product;quantity:number}>>(()=>{
    try {const stored=JSON.parse(localStorage.getItem('madarom_cart')||'[]');return Array.isArray(stored)?stored.filter(i=>i?.product?.id&&Number.isSafeInteger(i.quantity)&&i.quantity>0).slice(0,30):[]}
    catch{return []}
  }),[cartOpen,setCartOpen]=useState(false)
  useEffect(()=>{try{localStorage.setItem('madarom_cart',JSON.stringify(cart))}catch{}},[cart])
  useEffect(()=>{let cancelled=false;setCatalogError('');api<{stores:Store[];products:Product[]}>('/catalog').then(data=>{if(cancelled)return;setCatalog(data);setCart(items=>items.flatMap(i=>{const current=data.products.find(p=>p.id===i.product.id);let max=current?.stock||0;try{if(i.product.selected_variant)max=Math.min(max,JSON.parse(current?.variants_json||'[]').find((v:{name:string;stock:number})=>v.name===i.product.selected_variant)?.stock||0)}catch{max=0}const quantity=Math.min(i.quantity,max);return current&&quantity>0?[{product:{...current,stock:max,selected_variant:i.product.selected_variant},quantity}]:[]}))}).catch(e=>{if(!cancelled)setCatalogError(e.message)});return()=>{cancelled=true}},[retry])
  useEffect(()=>{api<{user:Account|null}>('/session').then(d=>setUser(d.user)).catch(()=>{}).finally(()=>setSessionLoading(false))},[])
  useEffect(()=>{window.scrollTo(0,0)},[location.pathname])
  useEffect(()=>{const path=location.pathname;const product=catalog?.products.find(p=>path===`/product/${p.id}`);const store=catalog?.stores.find(s=>path===`/store/${s.slug}`);const section=product?.name||store?.name||({'/catalog':'כל המוצרים','/stores':'חנויות','/account':'האזור האישי','/login':'כניסה והרשמה','/merchant':'אזור העסק','/admin':'ניהול המערכת'} as Record<string,string>)[path];document.title=section?`${section} | מדרום`:'מדרום | החנות שלכם';document.querySelector('meta[name="description"]')?.setAttribute('content',product?.description||store?.description||'מדרום — מוצרים וחנויות במקום אחד.');let robots=document.querySelector('meta[name="robots"]');if(!robots){robots=document.createElement('meta');robots.setAttribute('name','robots');document.head.append(robots)}robots.setAttribute('content',/^\/(admin|merchant|account|login|register|checkout)/.test(path)?'noindex,nofollow':'index,follow')},[location.pathname,catalog])
  function add(product:Product){let variant:Array<{name:string;stock:number}>=[];try{variant=JSON.parse(product.variants_json||'[]')}catch{return}const max=product.selected_variant?Math.min(product.stock,variant.find(v=>v.name===product.selected_variant)?.stock??0):product.stock;if(max<1)return;setCart(items=>{const existing=items.find(i=>cartKey(i.product)===cartKey(product));return existing?items.map(i=>cartKey(i.product)===cartKey(product)?{...i,quantity:Math.min(max,i.quantity+1)}:i):[...items,{product:{...product,stock:max},quantity:1}]});setCartOpen(true)}
  async function logout(){try{await send('/logout','POST');setUser(null)}catch(e){window.alert((e as Error).message)}}
  const stores=catalog?.stores||[],products=catalog?.products||[]
  const shop=(content:ReactNode)=>catalogError?<main className="wrap inner-page"><h1>לא הצלחנו לטעון את החנות</h1><p role="alert">{catalogError}</p><button className="button dark" onClick={()=>setRetry(v=>v+1)}>ניסיון נוסף</button></main>:!catalog?<Loading/>:content
  const session=(content:ReactNode)=>sessionLoading?<Loading/>:content
  return <><a className="skip-link" href="#main">דילוג לתוכן הראשי</a><Header count={cart.reduce((a,b)=>a+b.quantity,0)} user={user} onCart={()=>setCartOpen(true)}/><div id="main" tabIndex={-1}><Routes>
    <Route path="/" element={shop(<Home stores={stores} products={products} add={add}/>)}/>
    <Route path="/catalog" element={shop(<Catalog products={products} add={add}/>)}/>
    <Route path="/stores" element={shop(<Stores stores={stores}/>)}/>
    <Route path="/store/:slug" element={shop(<StorePage stores={stores} products={products} add={add}/>)}/>
    <Route path="/product/:id" element={shop(<ProductPage products={products} add={add}/>)}/>
    <Route path="/checkout" element={session(<CheckoutPage items={cart} clear={()=>setCart([])} user={user}/>)}/>
    <Route path="/for-business" element={<Navigate to="/catalog" replace/>}/>
    <Route path="/register" element={<Navigate to="/login" replace/>}/>
    <Route path="/login" element={session(<Login user={user} setUser={setUser}/>)}/>
    <Route path="/account" element={session(user&&user.role!=='customer'?<Navigate to={personalPath(user)} replace/>:<CustomerAccountPage user={user} onLogout={logout} onUserChange={setUser}/>)}/>
    <Route path="/merchant" element={session(<Merchant user={user} onLogout={logout}/>)}/>
    <Route path="/admin" element={session(<Admin user={user} onLogout={logout}/>)}/>
    <Route path="/privacy" element={<Info kind="privacy"/>}/><Route path="/accessibility" element={<Info kind="accessibility"/>}/><Route path="*" element={<Missing/>}/>
  </Routes></div><Footer/>{cartOpen&&<Cart items={cart} setItems={setCart} close={()=>setCartOpen(false)}/>}</>
}
